spring:
  application:
    name: service-a  #서비스를 구분할 name
server:
  port: 8801
eureka:
  instance:
    instance-id: inst001 # 동일한 서비스 name에서 인스턴스 구분자
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 클라이언트가 속할 Eureka Server